### ISSUE TITLE
Account for `catalyst_amount` in recipes

### ISSUE THREAD

**Issue by dbeckwith** [raiguard/Factorio-RateCalculator#13]
See [this discussion on MaxRateCalculator](https://mods.factorio.com/mod/MaxRateCalculator/discussion/5e551dc067ec67000d1c8630). Basically some products shouldn't be affected by productivity as determined by the [`catalyst_amount`](https://wiki.factorio.com/Types/ItemIngredientPrototype#catalyst_amount) property. This tripped me up when using RateCalculator because it shows some recipes using productivity having a net-positive loop when they shouldn't.

**Comment by raiguard** [comment]
Thanks for the report, this is fixed for the next release.

![image](https://user-images.githubusercontent.com/3515394/93291510-810a8600-f7a0-11ea-8cfe-a399f35d0151.png)
