### ISSUE TITLE
Incorrect Calculations for Plastic from Liquification

### ISSUE THREAD

**Issue by Roang-zero1** [raiguard/Factorio-RateCalculator#14]
#### Describe the Bug

The Rate Calculator incorrectly calculates a beaconed plastic setup.

The following setup is a fully beaconed 4 chemical plant setup (8 beacons/plant). This setup creates 2,8k plastic per minute.
See [Calculator](https://kirkmcdonald.github.io/calc.html#zip=fY5BCoUwDERv05UBxY+LSg+TH6sGo602Ct5exI2ICLN68ximQUVXQA65iY4CimH1Y3JRMCkT/HGxrf2ZMTSr+OR6j9sOgQVoQRp46mwsr9SptEWVCXe9fhr37Ud1PnhjIDyvvkVSDtNDOAA=)
This is also verified save below ([Editor Extensions](https://mods.factorio.com/mod/EditorExtensions) required)

#### To Reproduce

1. Load the Save Game
2. Use the calculator on the chemical plants
3. The calculator produces the following stats, this is off by about 700 plastic
![image](https://user-images.githubusercontent.com/12152679/93608387-d75b0d00-f9ca-11ea-9582-b99a01330924.png)

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

Save:
[MRC.zip](https://github.com/raiguard/Factorio-RateCalculator/files/5246054/MRC.zip)

Username:
Roang

#### Log file

Not a crash, can upload if needed.

**Comment by raiguard** [comment]
Thanks for the report. When I was fixing a bug related to catalyst amounts I accidentally reversed the calculation - I was only applying productivity bonuses to catalysts instead of only applying them to non-catalysts. Fixed for the next version.
