### ISSUE TITLE
Electricity calculation doesn't take into account efficiency modules

### ISSUE THREAD

**Issue by Omnifarious** [raiguard/Factorio-RateCalculator#15]
#### Describe the Bug

I use efficiency modules in electric furnaces. I have a line of 24 furnaces with tier 1 efficiency modules in both slots. This should result in a 60% reduction in electricity usage. The mod gives a total consumption of 1872 kilowatts. I believe this calculation to be wrong, even without factoring in the fact the efficiency modules were being ignored.

This calculation adds together the base (aka resting) consumption and the active consumption. I think, rather, that the base rate is the minimum consumption and so shouldn't be added to the active consumption. I have done tests to verify this in the past when calculating exactly how many solar panels would be needed to power the inserters for a line of boilers.

And, regardless of the correctness of that, this clearly isn't taking into account the effect of efficiency modules. Efficiency modules here should be shaving off 60% from the active consumption.

I believe that the correct calculation here gives 691.2 kilowatts of consumption for the whole line of 24 furnaces, each with two efficiency 1 modules.

Also, I have, sometimes, used efficiency modules with beacons on centrifuges as the total power reduction can actually offset the power consumption of the beacon. Centrifuges are power hungry beasts.

#### To Reproduce

1. Build a line of 24 furnaces and put efficiency 1 modules in them
 2. Use Alt-X (or whatever hotkey you use for the rate calculator)
 3. Select the whole line of furnaces
 4. Observe that it says they will consume 1872 kilowatts, which is not the correct figure

**Comment by raiguard** [comment]
Thanks for the report, but this is actually working properly. The calculator will show you the energy usage of something assuming that it is running 100% of the time. If you set up the furnaces so that they are actually being fed with items and smelting things, you will see that they consume 1.8 MW like the calculator says they do.

**Comment by Omnifarious** [comment]
You misunderstood me. I'll get a screenshot showing power consumption and your mod's idea of what the power consumption should be, just to make things extra-obvious.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/93655964-0c278e00-f9e4-11ea-9395-acaed3439e70.png)

Rate Calculator matches what the base game is reporting.

**Comment by Omnifarious** [comment]
> ![image](https://user-images.githubusercontent.com/3515394/93655964-0c278e00-f9e4-11ea-9395-acaed3439e70.png)
> 
> Rate Calculator matches what the base game is reporting.

I double checked myself. And I feel foolish. I should've checked the wiki for the normal power consumption for a furnace. The normal power consumption is 186 watts. *sigh* Thanks for not being mean about it.

**Comment by raiguard** [comment]
It's no problem, have a nice day!
