### ISSUE TITLE
Unrecoverable error when clearing belt type

### ISSUE THREAD

**Issue by DataBeaver** [raiguard/Factorio-RateCalculator#16]
#### Describe the Bug

When selecting transport belts as the calculation method, a belt type button appears.  The tooltip says "right mouse button to clear".  However, when cleared, an unrecoverable error occurs:

```The mod Rate Calculator (1.1.3) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RateCalculator::on_gui_elem_changed (ID 67)
__RateCalculator__/scripts/gui.lua:336: attempt to index local 'unit_data' (a nil value)
stack traceback:
__RateCalculator__/scripts/gui.lua:336: in function 'update_contents'
__RateCalculator__/scripts/gui.lua:107: in function 'handler'
__flib__/gui.lua:389: in function <__flib__/gui.lua:375>
```

#### To Reproduce

1. Start a new game with Rate Calculator enabled.  You may also want to have something that gives you quick access to an assembler, such as Creative Mod.
2. Place an assembler and select recipe for it (it probably doesn't matter which but I used Assembling Machine 1 with Transport Belt as the recipe)
3. Open Rate Calculator for the assembler
4. Select Transport Belts from the dropdown
5. Right-click the belt type button
6. An unrecoverable error occurs

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-RateCalculator/files/5249787/factorio-current.log)

**Comment by raiguard** [comment]
Thanks for the report, this has been fixed for the next release.
