### ISSUE TITLE
Idea: calculate steady state inputs

### ISSUE THREAD

**Issue by DataBeaver** [raiguard/Factorio-RateCalculator#17]
In complex production chains it can be hard to match the production and consumption rates of intermediate products exactly, if non-integer ratios or modules are involved.  This leads to Rate Calculator overestimating the required inputs.

As a simplified example, suppose item A takes 3 seconds to produce and requires two of item B, which only takes 2 seconds to produce and requires two of raw material C.  If you have one machine for A and two for B, you'll produce 20 A per minute and 60 B per minute.  Only 40 of those B are consumed each minute, so after buffers fill up the entire chain only requires 80 C per minute instead of 120.

In this simple example, having two machines for A and three for B would of course match perfectly, but in more complex chains with many different ratios it may require tens or even hundreds of machines to achieve perfect balance.  And without a perfect balance the errors accumulate through the chain so you may end up having entire extra machines in earlier stages if you simply build enough to satisfy the next stage's demands.

I would like to have a way for Rate Calculator to account for this and calculate the inputs based on only the items that can be consumed by further stages of the chain.  Items which are not consumed by any of the selected machines can be assumed to be outputs of the entire chain and should be accounted for at full production capacity.

**Comment by raiguard** [comment]
Sorry for the late response. I feel that this is straying into Factory Planner / Helmod territory. Rate Calculator is meant to tell you what the machines you selected are doing, not the ideal ratios for things. I will keep this in mind during my refactoring and see if it's simple enough to implement.

**Comment by AmericanPatriot6f0** [comment]
+1. This could be done with some sort of "0 net rate" button. 
![g1012](https://user-images.githubusercontent.com/68972888/108008087-5bcead80-6fb4-11eb-9ade-9e6ed7938521.png)

**Comment by raiguard** [comment]
@AmericanPatriot6f0 I guess I don't exactly understand what you mean. The mod should offset the inputs and outputs so that the net rate is always zero?

**Comment by raiguard** [comment]
Unfortunately, after giving it some thought, I have determined that adding this would involve increasing the mod's complexity by an order of magnitude, and using Helmod / Factory Planner esque logic to be able to handle all edge cases. That is out of scope for a mod such as this, and will probably never happen. If you want exact ratios, please use Factory Planner or Helmod.
