### ISSUE TITLE
wishlist: replace "actual crafting time" mod

### ISSUE THREAD

**Issue by slippycheeze** [raiguard/Factorio-RateCalculator#2]
I wish you would replace "[Actual Craft Time](https://mods.factorio.com/mod/Actual_Craft_Time)" instead.  ...or, at least, the one specific feature that I like most about it: the automatic nature of it.

The flow I most often use is:
1. Plop down a factory, and select a recipe for it.
2. Click the factory, and Actual Craft Time pops up telling me input, output, and belt consumption rates.
3. I click the "+1 / +5 factories/furnaces/whatever" button a few times to get the output rate I want.
4. Victory!

The flow I'd like to use is:
1. Press a shortcut button, and be prompted for the product and machine tier with sensible defaults.
2. Now follow steps two through four above.

The key difference is that your calculator is reactive: I can find out how much a collection of things can produce (and how much it'll consume, and what sort of belt feed I need to keep it happy), while Actual Craft Time can be used proactively to figure out how many factories I need.

That workflow covers the 95 percent case for Factory Planer for me: I rarely need to calculate the entire end-to-end production chain, just add one or two simple production lines and then make sure they stay fed.  Handle shortfalls by going and doubling production of whatever input fell short.

I love that I can use Rate Calculator to figure out the production of a collection of things, but I'd love it even more if it also supported this proactive "before I build a small thing" workflow.

The one other thing that'd be nice for the proactive use is if the GUI showed up without blocking the center of vision.  I'm not saying attached in the left side flow, but if possible a pop-up window I can move that was in the top left, or under the minimap, would be ideal.

You did achieve the goal of fitting with the game UI, though, amazingly well.  Good stuff!

PS: I know this is asking you to build something different from what you set out to make, and it'd be entirely legit to just say "no;" no upset or anything if this isn't interesting to you.

**Comment by raiguard** [comment]
Hey, thanks for the feedback!

I have been considering adding something akin to Actual Craft Time's functionality, but I'm not sure yet how I want to go about it. I'm not sure if I'll actually end up doing it.

Also, the window is draggable. Once you drag it somewhere it stays there even if you close it. You can re-center it by middle-clicking the frame title text.

I'm glad you enjoy the mod!

**Comment by raiguard** [comment]
I will eventually add this, because it's something that I also want.

**Comment by raiguard** [comment]
This will be in for v2.0.0 - the new `gui.relative` feature will make it quite nice to use!

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/101275091-46d9d080-3760-11eb-8586-7c31cd9af1a5.png)

So after experimenting with a relative GUI for a bit, I scrapped it and added a manual multiplier slider / textfield to the main interface instead. This allows you to use all of the different features of this GUI without me having to re-implement them in an entirely different GUI. The process is now like this:

1. Plop down a factory, set a recipe on it
2. Select it with the RC tool
3. Tab into the textfield and adjust up/down as needed

It's not _quite_ what you asked for, but it's pretty close!

**Comment by raiguard** [comment]
With the new version now released, you can achieve the same functionality as Actual Craft Time. It's not the exact same thing, but it's close enough. Closing this issue!
