### ISSUE TITLE
Showing Power

### ISSUE THREAD

**Issue by SergeantBlaze** [raiguard/Factorio-RateCalculator#21]
When selecting a group of working or non-working steam engines and their Boilers gives me zero results on Power Production

Below is 2 screenshots, one of the selection and the other of the results. I am playing on Pyblock.

https://imgur.com/a/MRqZxx6

I would have left a comment on the Factorio Mod Portal but I noticed you disabled all comments on all of your mods you produce. I currently use your recipe book, which works GREAT since FNEI doesnt work for modded playthroughs. So thank you for that.

**Comment by raiguard** [comment]
This is not a bug. The steam engines are being selected, but will only show fluid statistics, and boilers aren't supported yet at all. These are due to mod API limitations and will be added when Factorio 1.1 comes out.

**Comment by SergeantBlaze** [comment]
Thanks for quick response on this. I will continue to use this over the Max Rate Calculator mod since your UI is a bit better and the functionality seems more robust as well.
