### ISSUE TITLE
Include unpowered beacons in the calculation

### ISSUE THREAD

**Issue by JensForstmann** [raiguard/Factorio-RateCalculator#23]
#### Is your feature request related to a problem? Please describe.

When designing new layouts I start with the most important step (for me): the machines and how many I need, and so on. At this step I usually have no power available in the build due to the designing phase.

#### Describe the solution you'd like

I'd like that the Rate Calculator does include unpowered beacons into account.

**Comment by raiguard** [comment]
Unfortunately, all three of your requests are impossible to implement without a complete mod rewrite and a significant loss of performance. The mod works by reading the crafting machines' current bonuses directly, which is extremely fast and easy to do.

To do what you are requesting would require doing entity searches for every crafter to find beacons that are affecting them, which is horrendously slow and doesn't scale.

Ghost entities don't have bonuses at all until they are revived, so the mod would have to calculate everything manually on top of doing the beacon search.

So I'm sorry, but it's not going to happen. Thank you for using the mod!
