### ISSUE TITLE
Include requested modules into calculation

### ISSUE THREAD

**Issue by JensForstmann** [raiguard/Factorio-RateCalculator#25]
#### Is your feature request related to a problem? Please describe.

When designing new layouts I may not have the machines (esp. modules) with me. So it often happens, that the are requested to be place into machines by bots (but not available currently).

#### Describe the solution you'd like

I'd love to have Rate Calculator to include requested modules in machines and beacons into the calculation.

**Comment by raiguard** [comment]
Unfortunately, all three of your requests are impossible to implement without a complete mod rewrite and a significant loss of performance. The mod works by reading the crafting machines' current bonuses directly, which is extremely fast and easy to do.

To do what you are requesting would require doing entity searches for every crafter to find beacons that are affecting them, which is horrendously slow and doesn't scale.

Ghost entities don't have bonuses at all until they are revived, so the mod would have to calculate everything manually on top of doing the beacon search.

So I'm sorry, but it's not going to happen. Thank you for using the mod!
