### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by apaksl** [raiguard/Factorio-RateCalculator#27]
Thank you for updating this mod for 1.1 so quickly, I really like it so far. I really like that you have belts as a unit of measure, but if you have time, I would like to suggest you also add inserters.

**Comment by raiguard** [comment]
Yes, inserters are coming at some point. They're really complicated.

**Comment by apaksl** [comment]
sorry, i didn't mean to spam you, i'm not at all familiar with github. Seriously tho, thank you for the work you put into this mod!

**Comment by raiguard** [comment]
It's no problem, and you're welcome!
