### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pwnographic** [raiguard/Factorio-RateCalculator#28]
#### Describe the Bug
Caused error, said to report to you.

#### To Reproduce
Dragged the rate calculator on top of some labs mid-game in Krastorio 2 and this error occurred. Was working fine all game.

#### Save file & Username
Here is the latest autosave, if you run this save and repeat what I mentioned above, it will throw the error for sure.
https://gofile.io/d/2ayNgb

#### Log file
Current.log : https://hastebin.com/aqevuyecic.kotlin

**Comment by raiguard** [comment]
I was able to reproduce it, but I have absolutely no idea how or why the GUI got into that state, so there's not much for me to do about it. Disable and re-enable the mod in that save to fix it. If it happens consistently after that, please let me know so I can do some further investigation.
