### ISSUE TITLE
Furnace defaults

### ISSUE THREAD

**Issue by DocterDum** [raiguard/Factorio-RateCalculator#29]
When using the calculator on furnaces, if they aren't currently processing an item (therefore no recipe), they don't show any processing time, this makes it effectively useless when building blueprints for furnaces. 
Would it be possible to add a default furnace recipe setting or another way of selecting a recipe without live processing?

**Comment by raiguard** [comment]
I was thinking of doing something like this, but I've decided that it would be _way_ more effort than it's worth. Doing it properly would require me to copy the entity and all of the beacons affecting it to another surface, give it items, then measure its rate. I'm afraid that is far more complexity than I would like to introduce to the mod.

I'm sorry!

**Comment by DocterDum** [comment]
@raiguard 
I messed around a bit and managed to get this working by editing RateCalculator\scripts\calc\recipe.lua:

return function(rates, entity, emissions_per_second, prototypes)
	local recipe = entity.get_recipe()
	if entity.type == "furnace" then
		if not recipe then
			recipe = game.forces.player.recipes["iron-plate"]
		end
	end

I'm sure there's a much better way of writing all that, but would something along those lines be possible?

![iron-rate](https://user-images.githubusercontent.com/7615222/101748886-34291800-3b21-11eb-9e7d-0e1229f60385.png)

**Comment by raiguard** [comment]
I will take a look at some point and see if I can come up with an elegant solution.

**Comment by raiguard** [comment]
So, um, look at #53. Apparently there has been a LuaEntity property to do this this entire time! It will be in for the next version.
