### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by dmcdouga7** [raiguard/Factorio-RateCalculator#3]
![image](https://user-images.githubusercontent.com/66338341/83577386-09bb2a00-a502-11ea-9605-f02048ceda98.png)

used the rate calculator on a PySinkhole (which takes any fluid and voids it)

**Comment by raiguard** [comment]
I am unable to reproduce this error. Could you please send me the save file where this occured?

**Comment by raiguard** [comment]
Please provide a save file so I can test this!

**Comment by raiguard** [comment]
Closing due to lack of response.
