### ISSUE TITLE
Lab Rates

### ISSUE THREAD

**Issue by scotty9090** [raiguard/Factorio-RateCalculator#30]
I feel like I'm missing something obvious here, but here goes - My take away from the mod page is that the rate of science pack consumption for x number of labs would be shown by selecting them, but I'm getting nothing.  I've tried it with empty labs and with science packs loaded (but not actively researching).  What am I doing wrong?

**Comment by raiguard** [comment]
You need to be actively researching something. Science packs are consumed at a different rate per technology. :)

**Comment by scotty9090** [comment]
I was wondering ... thank you!
