### ISSUE TITLE
Rate only shows Max Rate

### ISSUE THREAD

**Issue by Jamie-McKernan** [raiguard/Factorio-RateCalculator#31]
I've got this mod and the max rate mod installed and they always show the same values. It seems to only show the max rate and not how much is actually being produced. A good example of this is where I compared the rate and max rate for some machines that didn't have enough ingredients so they weren't actually producing any items.

The rate mod still showed the same value as the max rate, even though the actual rate would be 0, as it wasn't producing anything. Do I have the wrong expectations of what this mod does? Or is this an issue?

I was looking at the rates for Assembly Machine 2.

**Comment by raiguard** [comment]
This is not a bug, the mod is working as intended. There's no way for me to get the "actual" rates without monitoring the entities over time. If you want that functionality, use [Assembly Analyst](https://mods.factorio.com/mod/assemblyanalyst).

**Comment by Jamie-McKernan** [comment]
> This is not a bug, the mod is working as intended. There's no way for me to get the "actual" rates without monitoring the entities over time. If you want that functionality, use [Assembly Analyst](https://mods.factorio.com/mod/assemblyanalyst) combined with either this mod or MRC.
> 
> If MRC didn't already exist then I would have called this mod by that name, since that's what it actually does.
> 
> Edit: I just noticed that in the mod description I said that it calculates the _average_ rates. That is an error, and I will fix it. Thank you for bringing it to my attention!

No worries! Thanks for linking the mod which will help me out! I will continue to use yours for the max rate! :) Quick response too :) Thanks for making a great mod.
