### ISSUE TITLE
when using it, the game crashed.(the new version published just now, may 2.0.0)

### ISSUE THREAD

**Issue by Tingamm** [raiguard/Factorio-RateCalculator#32]
399.060 Error MainLoop.cpp:1281: Exception at tick 2139062: 模组 速率计算器 [Rate Calculator] (2.0.0) 引发了无法恢复的错误。
请向模组作者报告此错误。

Error while running event RateCalculator::on_tick (ID 0)
__flib__/gui-beta.lua:136: attempt to index local 'elem' (a nil value)
stack traceback:
	__flib__/gui-beta.lua:136: in function 'recursive_update'
	__flib__/gui-beta.lua:165: in function 'update'
	__RateCalculator__/scripts/gui/selection.lua:379: in function 'update'
	__RateCalculator__/scripts/selection-tool.lua:166: in function 'iterate'
	__RateCalculator__/control.lua:167: in function <__RateCalculator__/control.lua:164>
 403.944 Quitting: user-quit.

**Comment by raiguard** [comment]
Wow, I'm an idiot. Unfortunately it will have to wait until tomorrow. I'm sorry. In the meantime, please revert to the previous version.

**Comment by raiguard** [comment]
Thanks, fixed for the next release.
