### ISSUE TITLE
Error loading save

### ISSUE THREAD

**Issue by Pwnographic** [raiguard/Factorio-RateCalculator#36]
#### Describe the Bug

I created a save, dropped a BP, saved game. Added a mod "No Power Icons" and then attempted to re-load that save and this error popped up.

#### To Reproduce

Load the save.

#### Save file & Username

https://gofile.io/d/xeaqkI 
Pwnographic

#### Log file

https://hastebin.com/getovehaga.yaml

**Comment by raiguard** [comment]
Thank you, fixed for the next release.
