### ISSUE TITLE
Graphical bug on shortcut buttons, key errors

### ISSUE THREAD

**Issue by Pwnographic** [raiguard/Factorio-RateCalculator#39]
#### Describe the Bug

Title.

#### To Reproduce

http://prntscr.com/vxq49t

#### Save file & Username

N/A See image http://prntscr.com/vxq49t

#### Log file

N/A See image http://prntscr.com/vxq49t

**Comment by raiguard** [comment]
This is not the fault of Rate Calculator. This is the Shortcuts mod naively making shortcuts for any selection tool. Please post a bug report on that mod's page.
