### ISSUE TITLE
Incorrect "net rate" figure with Space Exploration

### ISSUE THREAD

**Issue by Xon** [raiguard/Factorio-RateCalculator#4]
Space Exploration uses a number of probabilistic recipes which appear to confuse the heck out of the rate calculation.

I have this lab layout, which is is 24 telescopes + 2 labs in two batches, and some astrometrics lab doing UV and visible light observation data;
![image](https://user-images.githubusercontent.com/635541/87164883-eacb6700-c2fb-11ea-9953-47b88028a51a.png)

Selecting the top half;
![image](https://user-images.githubusercontent.com/635541/87164686-a63fcb80-c2fb-11ea-873b-f04c53e4c99b.png)

Selecting the bottom half;
![image](https://user-images.githubusercontent.com/635541/87165075-3716a700-c2fc-11ea-8c8c-5f2fdd185769.png)

Selecting both;
![image](https://user-images.githubusercontent.com/635541/87164698-a93abc00-c2fb-11ea-85ae-f89d3e21a291.png)

Yes, there is one lab with the wrong "type" but how if that causing a drop from net rate from 610 => 61 per minute?

Note; a couple QoL mods; but nothing which changes these recipies.

**Comment by Xon** [comment]
Also the recipes in question;
![image](https://user-images.githubusercontent.com/635541/87166710-878f0400-c2fe-11ea-8187-f606453652e4.png)
![image](https://user-images.githubusercontent.com/635541/87166790-a392a580-c2fe-11ea-8a5b-4061eca18586.png)
![image](https://user-images.githubusercontent.com/635541/87166902-cde46300-c2fe-11ea-9357-95d7d9811fb7.png)

(Hence why I really want to use a rate calculator tool)

**Comment by raiguard** [comment]
Could you send me your save file?

**Comment by Xon** [comment]
I've PM'ed you a link to the save file on the factorio forums.

**Comment by raiguard** [comment]
This is not a bug, it's working just fine. You're conflating the net rates of the UV observation frames and the visible observation frames. The net rate of the UV observation frames is dropping by 333.3, which is what that one extra lab is consuming.

The icons for those two things are FAR too similar, so I don't blame you for mixing them up. Sorry for the delay!
