### ISSUE TITLE
UX: Consider using icons instead of dropdown menu

### ISSUE THREAD

**Issue by nhat** [raiguard/Factorio-RateCalculator#40]
Currently we can display item rate in a time unit or belt via a dropdown menu. My main use case is switching between viewing items/second and items/belt. However using dropdown is cumbersome and unnecessary for only 4 possible options.

Please consider replace the dropdown menu with 4 icons, so that switching between different views would be faster (1 instead of 2 clicks).

Example:

![](https://miro.medium.com/max/4800/1*hJOOX1GncHWEJ63Z2UOmDA.png)

Additional ref: https://medium.com/@kollinz/dropdown-alternatives-for-better-mobile-forms-53e40d641b53

**Comment by raiguard** [comment]
Thank you for the suggestion, but I'm keeping it as it is. The problem with that method is that it's not scalable - I am trying to keep the GUI relatively compact so you can have it open on the side while configuring your setups. If I add more units of measure in the future (which I tentatively plan to), then the GUI would have to get wider.

Additionally, how would the UX of the choose elem button work? It would be a lot less intuitive in my opinion unless each units button had its own choose elem button next to it, which would take up even more space.

Thanks again for the suggestion.

**Comment by nhat** [comment]
Thanks for your swift reply!

A hotkey for rotating between all units would certainly help and I think it makes sense with or without implementing my suggestion.

FWIW, in my regular play I just want to know
1. how many belts are needed to supply the raw material
2. how many items are produces per second

With that in mind if would simply show 2 icons for each option and make the time scale configurable, since most users will just stick with 1 time unit. Also just leave the choose element button unmodified like now.

Again thanks for making and improving this mod.
