### ISSUE TITLE
2.0.2 crashes when selecting a miner that ran out of ore

### ISSUE THREAD

**Issue by baltoaca** [raiguard/Factorio-RateCalculator#41]
#### Describe the Bug

Mod crashes when selecting a miner that ran out of ore
This worked before the mod updated.

![err](https://user-images.githubusercontent.com/917454/101485712-31cd8f00-3964-11eb-8df9-a6729e6b32e7.png)

#### To Reproduce

1. Alt+X
2. Drag over a miner marked out of ore
3. See error

#### Save file & Username

username: baltoaca
The engineer is right next to the miner
Save file https://ufile.io/ykzufsie

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-RateCalculator/files/5659316/factorio-current.log)

**Comment by DeXoteric** [comment]
I'd like to add something. I don't think it matters if it's marked for deconstruction.

It crashes (same error) when there is no ore left and miner has red light.

**Comment by baltoaca** [comment]
> 
> 
> I'd like to add something. I don't think it matters if it's marked for deconstruction.
> 
> It crashes (same error) when there is no ore left and miner has red light.

Tested again and you are right, it has nothing to do with the deconstruction.

**Comment by einsteiner900** [comment]
I get the same thing, Factorio version 1.1.5, with exactly the same message.

**Comment by raiguard** [comment]
Thanks for the report, fixed for the next release.
