### ISSUE TITLE
Selecting an area with pumpjacks does not show rate

### ISSUE THREAD

**Issue by Riley19280** [raiguard/Factorio-RateCalculator#42]
#### Describe the Bug

When selecting an area wit h a pumpjack included, no rate is calculated/

#### To Reproduce

1. Select pumpjack
2. Observe no value is shown

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-RateCalculator/files/5685701/factorio-current.log)

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/102169474-8767d700-3e4f-11eb-9482-3e900bc39ffe.png)

Works fine for me. Make certain you don't have a chest or cargo wagon selected as your units.
