### ISSUE TITLE
Drop Down List remains open

### ISSUE THREAD

**Issue by Mattia2510MC** [raiguard/Factorio-RateCalculator#44]
#### Describe the Bug

When closing the GUI the drop down list remains open

#### To Reproduce

1. Use the calculator on something
2. Open the drop down list, but choose nothing
3. Press Escape to close the GUI

**Comment by raiguard** [comment]
This is strange, because I specifically de-focus the dropdowns when the GUI is closed. I don't think there's anything I can do about this if that's not working anymore.

**Comment by raiguard** [comment]
Gonna close this, because it's unfixable.
