### ISSUE TITLE
Factorissimo2 Buildings as Units

### ISSUE THREAD

**Issue by Mattia2510MC** [raiguard/Factorio-RateCalculator#45]
#### Describe the Bug

You can select the Factorissimo2 buildings as a unit to measure throughput

#### To Reproduce

1. Have the [Factorissimo2](https://mods.factorio.com/mod/Factorissimo2) mod installed
2. Use the calculator on something
3. Select units

**Comment by raiguard** [comment]
Thanks, fixed for the next release.
