### ISSUE TITLE
Fluid Consumption

### ISSUE THREAD

**Issue by Mattia2510MC** [raiguard/Factorio-RateCalculator#46]
#### Describe the Bug

The mod doesn't calculate how much fuel is consumed in a fluid burning boiler

#### To Reproduce

1. Have [Bob's Power](https://mods.factorio.com/mod/bobpower) installed
2. Place a Fluid Burning Boiler and provide fuel (here given with Editor Extension)
3. Use the calculator

![image](https://user-images.githubusercontent.com/76060177/102487798-6bd91800-406b-11eb-9ecd-b555ca5adc5c.png)

**Comment by raiguard** [comment]
That's strange, I specifically tested this before releasing the mod. Thanks for the report.
