### ISSUE TITLE
UI scaling issue when above 100% scale

### ISSUE THREAD

**Issue by mxdanger** [raiguard/Factorio-RateCalculator#47]
#### Describe the Bug

Using a UI scale higher than 100% results in the list becoming horizontally scrollable by a few pixels _only_ when the list has a vertical scrollbar.

##### Screenshots

100% scale:
<img src="https://user-images.githubusercontent.com/32040254/102664867-91802300-4138-11eb-9b12-070016baca73.png" alt="100% scale screenshot" width="500"/>

125% scale:
<img src="https://user-images.githubusercontent.com/32040254/102664816-744b5480-4138-11eb-99e3-aa36025ed18b.png" alt="125% scale screenshot" width="500"/>

#### To Reproduce

1. Go to Settings > Interface > UI scale set it to anything above 100%.
   * Also affects high-resolution monitors with automatic UI scale enabled.
2. Use the Rate Calculator to create a list that's tall enough to require a vertical scrollbar.

**Comment by raiguard** [comment]
Thanks, fixed for the next version.
