### ISSUE TITLE
Allow for vertically resizing the window

### ISSUE THREAD

**Issue by mxdanger** [raiguard/Factorio-RateCalculator#48]
#### Is your feature request related to a problem? Please describe.

When more than seven rows appear in the table you must scroll to see them all, this is annoying when there's no reason that it should be limited by that much. This causes many people to avoid using this mod due to the inconvenience.

#### Describe the solution you'd like

* Option 1: Add an option in the mod settings to change the maximum amount shown upon generating the table before the overflow scrolling is needed.
* Option 2: Allow the user to grab the corner of the window and/or the bottom edge, allowing them to drag to resize it.
  * Preferably the resizing should move in incremental steps according to the height of a table row.

**Comment by raiguard** [comment]
I went ahead and added a per-player setting for adjusting the number of visible rows, and increased the default number to ten. Implemented for the next version.
