### ISSUE TITLE
Support analysis in Edit-Blueprints mod

### ISSUE THREAD

**Issue by nonoroazoro** [raiguard/Factorio-RateCalculator#5]
Thanks and I love your mod! :smile: 

[Edit-Blueprints](https://mods.factorio.com/mod/Edit-Blueprints)

**Comment by raiguard** [comment]
If you're in the map editor, you need to be in the "none" tool in order to use selection tools.

Sorry, but that's just how the game works, and there's nothing I can do about it.

**Comment by nonoroazoro** [comment]
> If you're in the map editor, you need to be in the "none" tool in order to use selection tools.
> 
> Sorry, but that's just how the game works, and there's nothing I can do about it.

All right, I'll try. Thanks!
