### ISSUE TITLE
IR2 Incompatibility

### ISSUE THREAD

**Issue by Pwnographic** [raiguard/Factorio-RateCalculator#50]
#### Describe the Bug

Mod fails to load with IR2

#### To Reproduce

Industrial Revolution 2 and Rate calc are incompatible at the moment.

#### Save file & Username

Not necessary? 

#### Log file

https://pastebin.com/tvhAq7t1

**Comment by billbo99** [comment]
8.720 Error ModManager.cpp:1555: Error while running setup for tips-and-tricks-item prototype "rcalc-introduction" (tips-and-tricks-item): Dependency "introduction" does not exist.

**Comment by raiguard** [comment]
Thanks for the report. I fixed it by simply removing the dependency on the vanilla "introduction" tip.
