### ISSUE TITLE
Make multiple selections for a calculation

### ISSUE THREAD

**Issue by mitterdoo** [raiguard/Factorio-RateCalculator#56]
I have a logistic robot factory that has several assembly machines spread out. Some intermediate assemblers, however, aren't always in the same physical "cluster" of the final product they're contributing to; they can sometimes be spread out far apart from each other. If I want to use this calculator for certain assemblers, I either have to select all of them (including unrelated machines, cluttering the UI and slowing calculation times when desired machines are far apart), or select them individually and add up the numbers manually. It would be far easier if there was a way to make multiple selections for a single calculation. Or even a way to just add/remove machines from the last calculation that was made.

**Comment by raiguard** [comment]
In for the next version. Shift + selecting with the tool will append onto the previous selection instead of creating a new selection.
