### ISSUE TITLE
Handle recipes with the same fluid/gas but with different temperatures

### ISSUE THREAD

**Issue by billbo99** [raiguard/Factorio-RateCalculator#57]
#### Is your feature request related to a problem? Please describe.

Some of the recipes in Py take in fluid/gas at one temperature and output the same fluid/gas at a different temperature.

Recipe:   Hot-stone brick
Ingredients:   Warmer stone brick + Outlet gas (stage 4) >=1000C
Results:  Hot stone brick + Outlet gas (stage 4) 750C

#### Describe the solution you'd like

Have rate calculator treat the gas/fluids at different temperatures as different items to be calculated 

#### Additional context

![image](https://user-images.githubusercontent.com/17733206/105106863-aab91e00-5aae-11eb-9ca3-e022dbafed74.png)

Ideally there needs to be a column for temperature, or an overlay over the gas/fluid with the min temperature required.

![image](https://user-images.githubusercontent.com/17733206/105107410-f9b38300-5aaf-11eb-87ca-33dbd6e453ab.png)

**Comment by raiguard** [comment]
Recipe Book supports fluid temperatures now, but I'm not sure on how an implementation for this mod would work. But I'll definitely think about it.

**Comment by raiguard** [comment]
I added basic support for output temperatures. Input temperatures are probably not going to happen because they can be ranges, min/max, or explicit.

![image](https://user-images.githubusercontent.com/3515394/144504552-8323fee8-d9b2-42f5-97f3-3593f8345790.png)
