### ISSUE TITLE
Support for more buildings

### ISSUE THREAD

**Issue by kuxynator** [raiguard/Factorio-RateCalculator#59]
As I noticed not all buildings are supported.
https://mods.factorio.com/mod/mini-machines
https://mods.factorio.com/mod/micro-machines
I don't know how it was implemented, but a generic approach would automatically support (almost) all modded buildings.

Best regards and thanks for this mod.

**Comment by raiguard** [comment]
RC _does_ have a generic approach. I just tested the mini-machines mod and it works fine.

**Comment by herman925** [comment]
Can I add a request to have it compatible with detecting machines within Factorissimo2?

**Comment by raiguard** [comment]
Reading machines in Factorissimo buildings isn't going to happen, that would be a huge amount of complexity. However, in the next version you'll be able to append your previous selection by holding shift, so you can make selections in multiple buildings to see how they interact.
