### ISSUE TITLE
new feature: Power Consumption

### ISSUE THREAD

**Issue by TheoMarque** [raiguard/Factorio-RateCalculator#6]
I wish see maximum power that machines consume I t will be very useful to plan power consumption of outpost and using power switches and accumulator backup systems or emergency powersource.

**Comment by raiguard** [comment]
That's a great idea! I'll add it in.

**Comment by TheoMarque** [comment]
Great!.  You separate power consumption to machines (assemblers, refineries), logistic devices (inserters, pumps, roboports, beacons) and power plants (solars, steam engines, turbines and... Accumulatros)
It might be little innacuracy for some situations, so I think, only max, peak power consumption will be useful.

**Comment by raiguard** [comment]
As with everything else in the mod, it'll be an average. I am currently considering a few ways to go about it. Right now my plan is to make it a switch that you can toggle between item/fluid rates and power rates, so it can re-use all of the same UI for both.

**Comment by TheoMarque** [comment]
But average is not good measure because, assemblers have "drain".
Similar problem is with inverters - mass inserter power is 133 kW but the average will be low. For example if we have (un)loading station with 12 mass inserters for one wagon, power peak can rails to 1,6 MW ( ~9,5 MW for 6 cargo wagon).  So, I think about max power for whole setup to avoid hitting max power, but average power measure is good for assemblers and other machines.

**Comment by danrayson** [comment]
I came here specifically to ask for a power consumption addition, but someone already did!  BUMP!

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/90843862-d083a080-e31f-11ea-9ae9-211687f6ec22.png)

I have an initial prototype going. It is displaying the max power consumption, like what was suggested. Therefore, things like roboports that vary wildly in their real-world consumption will not be very accurate. But, it's better than nothing!

I am also working on power production.

**Comment by raiguard** [comment]
So after neglecting this for a while, I'm back to working on it. The mod will show electric consumption for any and all machines, but will only show production for solar panels due to mod API limitations. I am working to get production for generators and burner generators added for Factorio 1.1.

Thank you for your patience!

**Comment by raiguard** [comment]
Power consumption is out now. Like I said, generators and burner generators are not supported yet, and won't be until Factorio 1.1. But the rest of it works!

![image](https://user-images.githubusercontent.com/3515394/93273772-f6ad2c80-f775-11ea-8e6c-62e67929e0a0.png)

**Comment by TheoMarque** [comment]
Some problem with beacons and power consumption. For example:

Modded furnace consume 248kW (but for vanillia situation is the same)

If I feed it by 4 speed 3 modules and surround it by 12 beacons with the same modules - your mod shows only base power consumption. Real (beaconed and modules) consuption is 2980kW.

**Comment by raiguard** [comment]
Thank you, I've fixed that for the next release.
