### ISSUE TITLE
Ability to copy rates

### ISSUE THREAD

**Issue by Arkhorse** [raiguard/Factorio-RateCalculator#60]
#### Is your feature request related to a problem? Please describe.

The ability to copy the rates, totals, and other numbers displayed could be nice. I use a global circuit network to calculate when I need to add things like power and raw resources. For the most part I dont need to directly copy things. But with power, I need to open the signal multiple times to set the correct watts (I dont use MW). This is also due to me having a poor memory :P

#### Describe the solution you'd like

Could have a new tab to copy the numbers from the other tabs, or just allow highlighting and copying directly where they are displayed. Could even have the ability to export the numbers you want directly to a constant combinator, then place that in the players cursor. But I have no idea how complicated that might be (Maybe using a blueprint style thing?)

#### Additional context

n/a

**Comment by raiguard** [comment]
This seems like a pretty niche feature, sorry. I don't think it'll happen.
