### ISSUE TITLE
Incorrect lab speed calculation in modded labs

### ISSUE THREAD

**Issue by Soul-Burn** [raiguard/Factorio-RateCalculator#61]
In the Industrial Revolution 2 mod, there are different labs with different "researching_speed" values (1, 2 and 8).
The entity is modified with 'data.raw.lab["lab"].researching_speed = speed'
In the wiki, labs have this property as seen [here](https://wiki.factorio.com/Prototype/Lab#researching_speed).
Rate calculator seems to ignore *this* modifier on the entity.

1. Use Industrial Revolution 2 mod.
2. Place an electric laboratory.
3. Check rate calculator on the laboratory.
4. Compare to actual rate and indicated speed on item.

The save is next to the electric laboratories.
I have tech for 140% bonus lab speed + productivity modules. Without modules, the indicate rate on the building is 4.8. With modules it's 3.84 (-20%). All tech in this mod is 60 seconds. Therefore 3.84 per minute.
The rate calculated by Rate Calculator is exactly half, 1.92

#### Save file & Username

[NNN5.zip](https://github.com/raiguard/Factorio-RateCalculator/files/6049698/NNN5.zip)

This is a single player save, not sure about the username, but it is probably "Soul-Burn"

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-RateCalculator/files/6049708/factorio-current.log)

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/109618715-1bfbe000-7af5-11eb-8ead-0b28b4d5094c.png)

Huh, you're right. I'll have a look tomorrow.

**Comment by raiguard** [comment]
Fixed for the next release. The calculation wasn't taking into account the lab's base speed bonus as defined in the prototype.
