### ISSUE TITLE
non-recoverable error

### ISSUE THREAD

**Issue by npuldon** [raiguard/Factorio-RateCalculator#63]
#### Describe the Bug
non-recoverable error

#### To Reproduce
I was afk when it happened so not doing anything in particular.  It crashed the game and my friend who was on the server got booted and sent me a discord message to check the server so here I am.
4. See error: https://imgur.com/a/vxrkMuP

Be certain to reproduce the issue on the same save file that you upload. <<--- I can not.  Hopefully you can understand the issue from the imagine and log file.

#### Save file & Username
username: npuldon
84MB save file (K2 + SE Modpack): https://drive.google.com/file/d/1r6JAdhVPoKOIO6cES0hkFx0sqkcjMDJX/view?usp=sharing

#### Log file
[factorio-current.log](https://github.com/raiguard/Factorio-RateCalculator/files/6066565/factorio-current.log)

**Comment by raiguard** [comment]
Well, I can band-aid this, but that doesn't fix the underlying problem of why an entry didn't have an output amount. It shouldn't ever be `nil`. So if you ever manage to reproduce it, please let me know!

I like your base by the way. And I see that I have thoroughly invaded your mod list. :D

**Comment by npuldon** [comment]
yes, you do good work and I appreciate it.   I'm glad you like the base too!  

Cheers

**Comment by raiguard** [comment]
Going to close. Please reply to this issue if you get this again, and I'll re-open it.
