### ISSUE TITLE
Fuel Refinery not selected when in space

### ISSUE THREAD

**Issue by adugaue** [raiguard/Factorio-RateCalculator#67]
#### Describe the Bug

When an fuel refinery is placed in space rate calculator does not select it.

#### To Reproduce

1. Go to an orbit/asteroid belt/asteroid field
2. Place a fuel refinery
4. Try to select with rate calculator

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

You said I didn't have to upload one but if you need it lemme know! - Flood

**Comment by raiguard** [comment]
[Discord tracking link](https://discord.com/channels/419526714721566720/571307840682328065/835734590856626246).

Summary: this is happening because some entities are created in SE postprocess, which runs after Rate Calculator's data-final-fixes.

**Comment by raiguard** [comment]
Fixed for the next version.
