### ISSUE TITLE
Pollution calculator doesn't account for modded modules that affect pollution directly (e.g. Space Exploration modules)

### ISSUE THREAD

**Issue by Wiwiweb** [raiguard/Factorio-RateCalculator#68]
#### Describe the Bug

Pollution calculator doesn't account for modded modules that affect pollution directly (e.g. Space Exploration modules)

See picture:

![image](https://user-images.githubusercontent.com/4723472/116003014-22687e80-a5b1-11eb-86e9-b05aced1a79e.png)

These Space Exploration production modules add +40% pollution for a total of 14 pollution / min but Rate Calculator only sees the 10 / min from electricity usage.

#### To Reproduce

1. Put some modded modules that influence pollution directly in an assembler (e.g. Space Exploration modules)
2. Calculate rate
3. Rate doesn't account the flat pollution modifier

#### Save file & Username

[rate calculator pollution.zip](https://github.com/raiguard/Factorio-RateCalculator/files/6372551/rate.calculator.pollution.zip)

Username: Wiwiweb

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-RateCalculator/files/6372553/factorio-current.log)

**Comment by raiguard** [comment]
Thanks, fixed for the next version.
