### ISSUE TITLE
Tutorial hints re-enable every time the mod is unloaded+loaded

### ISSUE THREAD

**Issue by biomatter** [raiguard/Factorio-RateCalculator#70]
#### Describe the Bug

Every time I log in to my single-player world I get the hint in the bottom-left corner of my screen with the 'How To Use' stuff tip system from base Factorio despite me marking them as 'Read'. I think this is happening because I'm playing on a friend's server between single-player sessions and he does not have the mod. Just conjecture, sorry if this isn't helpful or is actively misleading.

#### To Reproduce

1. Load save with mod.
2. Mark all tips as read.
3. Exit save, unload mod.
4. Load world2 without mod.
5. Exit world2.
6. Load first world with mod.
7. Tips again???

**Comment by raiguard** [comment]
Sorry, I can't fix this. This will happen with any mod that adds tips.

**Comment by biomatter** [comment]
Oh, really? Sorry for the bother then.
