### ISSUE TITLE
Take into account recipes with multiple outputs

### ISSUE THREAD

**Issue by ColonelPhantom** [raiguard/Factorio-RateCalculator#76]
#### Is your feature request related to a problem? Please describe.

In Space Exploration, some recipes output multiple units of a product (e.g. green science). The rate calculator does not seem to take this into account, saying that 10 green science assemblers produce 1 green science per second. This should be 20, since every 10 seconds 1 assembler produces 2 packs.

#### Describe the solution you'd like
Take these output multipliers into account

**Comment by raiguard** [comment]
The mod does do this already. You're probably using assembling machine 1's, which have a crafting speed of 0.5. If you hook up the inputs and look at the production graph, you'll see that Rate Calculator is correct.

![image](https://user-images.githubusercontent.com/3515394/144483759-47d803a1-39c9-4629-9cbe-d91c93441b05.png)
