### ISSUE TITLE
Fine number adjust

### ISSUE THREAD

**Issue by Gapi34** [raiguard/Factorio-RateCalculator#79]
#### Is your feature request related to a problem? Please describe.

So it's kind annoying when i want to increese the number of machinse in the menue by one since there is only a slider.

#### Describe the solution you'd like

i think an easy soluting would be to eather add arrows next to the number for increesing or decreesing by one, or add little +1,+5,+10 and the oppisot on the other side.

#### Additional context

Love the mod other wise is very grate and much more usful with the heat and energy options than max rate calculator

**Comment by raiguard** [comment]
You can type into the textfield as well, and you can use the scroll wheel on the slider to adjust it precisely. I don't think there's really a need for a bunch of buttons.
