### ISSUE TITLE
Crash error with space exploration

### ISSUE THREAD

**Issue by Xon** [raiguard/Factorio-RateCalculator#8]
Error while running event RateCalculator::on_gui_elem_changed (ID 67)
 __RateCalculator__/scripts/rcalc-gui.lua:210: attempt to index local 'unit_data' (a nil value)
 stack traceback:
         __RateCalculator__/scripts/rcalc-gui.lua:210: in function 'update_contents'
         __RateCalculator__/scripts/rcalc-gui.lua:62: in function 'handler'
         __flib__/gui.lua:352: in function 'dispatch_handlers'
        __flib__/gui.lua:138: in function <__flib__/gui.lua:138>"

Can provide a save if requested.

**Comment by Xon** [comment]
Occurred when changing from the "deep space belts" to express belts

**Comment by raiguard** [comment]
Yes, please provide a save file.

**Comment by raiguard** [comment]
Closing due to lack of response.
