### ISSUE TITLE
window won't pop up anymore

### ISSUE THREAD

**Issue by M3wM3w** [raiguard/Factorio-RateCalculator#80]
It worked for a while, then it stopped working.
Window no longer pops up when selecting buildings with the tool.
Maybe a multiplayer gui issue??
No errors in current.log

**Comment by raiguard** [comment]
Please send me the save file.

**Comment by M3wM3w** [comment]
https://www.file-upload.net/download-14782434/pyanodon2021_03_03.zip.html

**Comment by raiguard** [comment]
Sorry for the delay. I just loaded your save file, and the GUI opens just fine for me. Are you still experiencing this issue?

**Comment by raiguard** [comment]
If you get this again, please let me know.
