### ISSUE TITLE
Menu list is kept unfolded(UI bug)

### ISSUE THREAD

**Issue by Kinetic27** [raiguard/Factorio-RateCalculator#82]
#### Describe the Bug

As shown in the picture below, the menu list is kept unfolded.
![image](https://user-images.githubusercontent.com/39849944/146670205-58537c07-9c76-41ce-86c1-132fbcf5b95c.png)

#### To Reproduce

1. Use rate calculator to turn the UI
![image](https://user-images.githubusercontent.com/39849944/146670231-d0404ef6-f0df-4c29-9cc5-b8da5b654543.png)

2. Open measure button
![image](https://user-images.githubusercontent.com/39849944/146670242-08222ef6-73ff-4407-b1f1-c24d57cc8231.png)

3. Press ESC. (You can't press the close key, but it closes with the esc key)

![image](https://user-images.githubusercontent.com/39849944/146670361-7c062660-af84-43c5-8f8a-2ffa6e3029e8.png)

#### Save file & Username

Username: Kinetic27
Save file: https://drive.google.com/file/d/1nXQbiq0xgPLPJsP2v2pzm0mJnOl4eM_6/view?usp=sharing
(Any save file is an error that occurs, so I think you don't need it.)

#### Log file

Attach `factorio-current.log`, found in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).

[factorio-current.log](https://github.com/raiguard/Factorio-RateCalculator/files/7740549/factorio-current.log)
[factorio-previous.log](https://github.com/raiguard/Factorio-RateCalculator/files/7740550/factorio-previous.log)
(It's not a fatal error, so there won't be much in the log.)

**Comment by raiguard** [comment]
This is a vanilla bug that I cannot fix.

**Comment by Kinetic27** [comment]
Oh.. I see...
