### ISSUE TITLE
Allow to specify inserter source

### ISSUE THREAD

**Issue by Pzixel** [raiguard/Factorio-RateCalculator#83]
Here is an example of the problem: https://www.reddit.com/r/factorio/comments/rlkalr/why_stack_inserter_cannot_keep_up_with_a_blue/

UI incorrectly shows that 0.85 inserters is enough to keep up with assembler speed but it incorrectly assumes that it's grabbing items from the chest. Grabbing from belt is considerably slower which in some cases may lead to incorrect assumptions. In a linked example this error becomes significant so machines get idle.

I suggest to implement some way to choose when items are grabbed from say requester chest or from the belt, with belt being the default. 

Even if it won't be ideal because it doesn't consider other inserters grabbing from the same belt it still would be much more accurate. And maybe it would be actually perfect that it will always give correct results

**Comment by raiguard** [comment]
This is already a thing. If you select an inserter that is grabbing from a belt it will adjust accordingly.

**Comment by Pzixel** [comment]
As per video I posted I was selecting a specific machine and specific inserter yet I've got 0.885 on a fully compressed belt. It looked like it's not correct so I assumed this functionallity wasn't implemented. If it was then I assume it might be a bit flawed.

Thanks for response. Awesome mode btw, helps me immensely!

**Comment by Pzixel** [comment]
Here is the problem illustrated:

![image](https://user-images.githubusercontent.com/11201122/147014654-82ae575f-a9e4-4e9e-823d-f87182dfa0a0.png)

There is only one inserter and you can see "Ingredient shortage". Hence I suspect it doesn't properly calculate belt-assembler moving speed

**Comment by raiguard** [comment]
I will take a look at this when I get a chance. Thanks for reporting!

**Comment by raiguard** [comment]
Sorry for the delay. I replicated your setup and ran it for two hours (sped up, of course), and it worked flawlessly. Assembly analyst reported zero downtime.

Keep in mind that there is no way to accurate predict inserter rates. The rates that rate calculator shows are an estimate only.

![image](https://user-images.githubusercontent.com/3515394/154784907-03c6178a-734d-4fb8-94f8-c05dee1d3479.png)

**Comment by raiguard** [comment]
I have added a warning that inserter <-> belt rates can be inaccurate. Since there is no way to accurately measure these rates, this is the best I can do. I'm sorry.

![image](https://user-images.githubusercontent.com/3515394/154864390-f8ffd9a2-27e7-42b4-81cf-d9c146bfc50a.png)
