### ISSUE TITLE
Ghost calculation

### ISSUE THREAD

**Issue by ray1claw** [raiguard/Factorio-RateCalculator#93]
#### Is your feature request related to a problem? Please describe.

Before constructing my setups, I tend to lay out the building layout using ghosts first with my roboport off. This allows me freedom to move and tweak without worry. Also, sometimes, I'm building a set up (eg an iron smelting line) and I would be missing some machines to be able to finish it. In either of these cases, the one thing I miss the most is the unability to include the ghost buildings in the rate calculation.

#### Describe the solution you'd like

A simple solution: the ability to select ghosts for calculation as well when I draw a selection box with the rate calculator. This could even be the default setting (since I can't currently think of why would most people want this to be off)

**Comment by raiguard** [comment]
This is actually not feasible. When an entity is a ghost, I can't read any of its properties. Max rate calculator gets around this by inferring a ton of things and doing a bunch of expensive calculations.

For example, if you selected an assembler ghost, I wouldn't be able to read its bonuses. So I would have to search for all beacons that may be affecting it and total that up manually. There are many things that simply cannot be calculated when they're ghosts.

Sorry, but this isn't going to happen. It would be convenient, but it's not feasible.
