### ISSUE TITLE
Inverse Net machines

### ISSUE THREAD

**Issue by AndreKR** [raiguard/Factorio-RateCalculator#94]
![image](https://user-images.githubusercontent.com/1188538/156946973-f404d3c6-97f1-483c-a61f-e58ef6cd3936.png)

Here I'm producing 16 enriched ore/s  and consuming 3.75.

The *Net machines* column tells me that I have 0.7656 producers too many. I don't know what to do with this number.

The complement (1 - 0.7656) of that number, 0.2344, would already be a bit more helpful. It would tell me that my producers are working at 0.2344 (≈ 24%) of their capacity.

But what I usually want to know is the reciprocal (1 / 0.2344) of that: 4.26. That tells me that I need 4.26 times the consumers than I have. The actual number of consumers I need would also be fine, in this case however that would be 4.26 as well because I only selected one consumer.

**Comment by raiguard** [comment]
The complement breaks down as soon as you get a number over 1.0 (1 - 1.2 == -0.2). That's not -0.2% of their capacity.

In any case, I'm not sure that I want to change this. Net machines is a very logical step from net rate, and it's super easy to plop down another consumer and take another measurement.
