### ISSUE TITLE
Allow measuring fluids using pipes

### ISSUE THREAD

**Issue by Dominiquini** [raiguard/Factorio-RateCalculator#96]
#### Is your feature request related to a problem? Please describe.

I cam measure items using transport belts as unit of measure. Would be cool if we can select pipes as unit of measure of fluids!

#### Describe the solution you'd like

Like transport belts, let the user select pipe to measure fluids. Also allow user select custom pipes added by mods...

#### Additional context

Like inserters, you could add pumps too (including modded pumps).

Thanks

**Comment by raiguard** [comment]
I don't think this would be very useful. It sounds like what you are looking for is pipe throughput, which is nearly impossible to accurately estimate for something like rate calculator. And I don't see how pipe volume would be useful.

I don't plan to add this, but patches are welcome.
